### PR TITLE
Add Swift package manager

### PR DESCRIPTION
**Pull request by ned1988**
### Changes

Support of Swift package manager

### References

Please include relevant links supporting this change such as a:

[Issue #92](https://github.com/auth0/JWTDecode.swift/issues/92)

### Testing

Can be tested by adding it as dependency in one of your projects.

* [x] This change adds unit test coverage
* [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] All existing and new tests complete without errors
* [x] All active GitHub checks have passed

### CODE REVIEW

**Comment by ned1988** [comment]
Damn, I haven't seen that there is already PR with `SPM` 😄

**Comment by ned1988** [comment]
Can somebody update me please if this `PR` is something interesting for you guys?

**Comment by cocojoe** [comment]
Thanks @ned1988 for your PR, yes it is interesting and we will take a look at it soon.

**Comment by cocojoe** [comment]
Thanks for the PR @ned1988 we had to make some additional checks and small tweaks so moved this into #97 I'll close this pR.

**Pull request closed without merging**
