### PR TITLE
add watchOS support

### PR DESCRIPTION
**Pull request by jkandzi**

### CODE REVIEW

**Comment by cfraz89** [comment]
Hey jkandzi,

Not a maintainer, but wanted to use your watchOS fork. I noticed that the watchOS scheme here isn't marked as shared, which makes it unavailable in Carthage. Could you consider toggling that?

**Comment by jkandzi** [comment]
done. is it working now?

**Comment by hzalaz** [comment]
@jkandzi thanks for the PR, will try to review by EOW or start of the next one. In the meantime, can you try running the tests for watchOS in travis?

**Comment by cfraz89** [comment]
@jkandzi The scheme didn't build for me, as a couple of flags in the pbxproj seemed to deny it from matching up to a target device when building.

I've poked it until it builds for me, and I'll make a PR for your fork. Can you see if it didn't break anything for your/other use cases?

**Pull request closed without merging**
