### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by thedavidharris**
### Changes

Adds support for the Swift Package Manager

### Testing

* [x ] This change has been tested on the latest version of the platform

### Checklist

* [ x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ x] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

This is a draft for now as there a few things that should be discussed/addressed:
- Is the folder convention for Tests alright? Should the project move to a Sources/Tests configuration more like SPM supports by default and use the `exclude` directive?
- The Package.swift should explicitly identify platform support; what should these values be set at? CIn theory, this allows WatchOS support even without https://github.com/auth0/JWTDecode.swift/pull/91
- How should a CI job checking that `swift test` executes successfully be added?

### CODE REVIEW

**Comment by cocojoe** [comment]
Thanks for starting this, although looks like you've renamed files, what's the requirement behind this? Although these changes are not reflected in the project so it doesn't build anymore :)

**Comment by thedavidharris** [comment]
@cocojoe should be cleaner now. The file moves are a mix of meeting the SPM folder structure, as well as getting around the fact that it can't build mixed-language targets. 

The Objective-C tests fail on importing Quick/Nimble/JWT headers, so those don't seem to be working with SPM, hence they're commented out.

**Comment by VladimirHorky86** [comment]
Hi, what's the status of it? It would be really great to use it with Swift PM.

**Comment by cocojoe** [comment]
Thanks for the inspiration on this PR, we're consolidating everything into #97

**Pull request closed without merging**
