### PR TITLE
Added watchOS support

### PR DESCRIPTION
**Pull request by jklp**
Added a target for watchOS.  Couldn't add the test target as couldn't get Nimble/Quick to build on watchOS.

### CODE REVIEW

**Comment by cocojoe** [comment]
Apologies I've not had time to try this, it looks okay at a glance, although not being able to run test is not ideal. I would like to take a look at that, to set expectation I'm on vacation so will be a bit delayed in response. Thanks

**Comment by jklp** [comment]
No worries, fwiw we've been running on WatchOS for the last couple weeks here and haven't run into any problems 🙂

**Comment by cocojoe** [comment]
@jklp please update README with watchOS support.

**Comment by jklp** [comment]
@cocojoe Hi, I updated the podspec and tested (and it works) though I might need some help with the other 2 items.  I'm not 100% on what to update in the README (I can't find anything which would be platform specific to watchOS) and I'm not sure what you mean by the dependency version (sorry!)

**Comment by cocojoe** [comment]
@jklp fair question as there was no existing WatchOS support, what's the minimum version that can be specified in the project? Would be ideal to match our other libraries e.g. https://github.com/auth0/Auth0.swift#requirements

When I said dependency I mean the deployment version in the PodSpec should match the project.

I would use the newer swift versions syntax as well which is demonstrated here for language version support in this PR. https://github.com/auth0/Auth0.swift/pull/279

**Comment by jklp** [comment]
@cocojoe Hey sorry for the long delay. I've just updated the README.md and also dropped the watchOS version to 2.0 to match the rest the project. Please let me know if there's anything else. Thanks!

**Comment by dylanmoo** [comment]
Is this pull request ready to be merged? With Auth0 SIWA available on apple watch as of iOS 13, it would be helpful to be able to read the JWT token on the Watch Extension itself.

**Comment by cocojoe** [comment]
#58

**Pull request merged**
