### PR TITLE
Migrated project to Swift 5

### PR DESCRIPTION
**Pull request by jjatie**
### Changes

- Swift version bumped to 5
- Quick version bumped to 2.x
- Nimble version bumped to 8.x

### References

- support ticket #85 

### Testing

No code changes made. All unit test still build and pass.

### Checklist

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

### CODE REVIEW

**Comment by cocojoe** [comment]
@jjatie Thanks, the hardest part is deciding to do a new major, as it feels it is time to follow suit of Quick/Nimble and drop Swift 3.x as both of these Libs no longer support it.  Although you should be able to fix your PR to ensure 4.x runs. Not ready to drop that yet.

**Comment by jjatie** [comment]
@cocojoe I'm not sure why the iOS builds are failing. My only guess is that it might have something to do with the Carthage caching?

**Comment by cocojoe** [comment]
Screenshot 2019-04-04 at 15 09 19

So the migration here is a little more complicated, there are older tests for ObjC. This is also not supported now in Quick/Nimnble.

**Comment by jjatie** [comment]
@cocojoe Regarding dropping Swift 3 support seems like the obvious choice. It would require work just to be able to support tests for Swift 3. Swift 4 has been around for over 1.5 years.
Maintaining an app for modern Apple platforms requires the use of Swift 4, and for non-Apple platforms SPM (when it is introduced) solves any Swift version issues since 4/5 are source compatible.

**Comment by jjatie** [comment]
> Screenshot 2019-04-04 at 15 09 19
> 
> So the migration here is a little more complicated, there are older tests for ObjC. This is also not supported now in Quick/Nimnble.

I thought that might be the case, but couldn't find any mention of that in their release notes.

**Comment by cocojoe** [comment]
I remember seeing it in https://github.com/Quick/Nimble/releases/tag/v8.0.0

`Migrate to Swift 4.1 and drop Swift 3.x support #515`

**Comment by quver** [comment]
Hello, what is the status of this pull request?

**Comment by cocojoe** [comment]
Tests don't pass, it will not be accepted like this.

**Comment by jjatie** [comment]
@quver @cocojoe The one objective-c test we have doesn't pass because of the updates to Quick/Nimble.

**Comment by cocojoe** [comment]
Thanks for the PR, I had a pass on this in #88

**Pull request closed without merging**
