### PR TITLE
Builds SPM dynamic library

### PR DESCRIPTION
**Pull request by JackoPlane**
### Changes

Build dynamically linked library

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

* [ ] This change adds unit test coverage
* [ ] This change has been tested on the latest version of the platform/language or why not

### Checklist

* [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ ] All existing and new tests complete without errors
* [ ] All active GitHub checks have passed

### CODE REVIEW

**Comment by Widcket** [comment]
Hi @JackoPlane, why do you need to dynamically link this library?

**Comment by JackoPlane** [comment]
We have a use case where our main app is using the Auth0 login SDK and another of our 3rd party frameworks also links `JWTDecode` for the same app causing issues of linking to duplicate frameworks.

**Comment by Widcket** [comment]
@JackoPlane we won't change the `type` of the library, but another library can be added and declared as dynamic.
Example:
```swift
.library(
        name: "JWTDecodeDynamic",
        type: .dynamic,
        targets: ["JWTDecode"])
```

**Comment by Widcket** [comment]
Let me know if you're interested in pursuing this further.

**Comment by Widcket** [comment]
Closing due to inactivity.

**Pull request closed without merging**
