### PR TITLE
Add tvOS Support

### PR DESCRIPTION
**Pull request by adolfo**
Added a `tvOS` target, build scheme, and tests to the Xcode project. 
Updated the `podspec` to include the `tvos` platform.

### CODE REVIEW

**Comment by adolfo** [comment]
Looks like CI is failing as the build script is expecting carthage version 0.10.0, but a newer version is installed.

**Comment by hzalaz** [comment]
@adolfo can you rebase it with `master`?, it should take care of the build error.

**Comment by adolfo** [comment]
@hzalaz Here you go. Let me know if you need this squashed.

**Comment by hzalaz** [comment]
Thanks, I can squash commits from Github

**Pull request merged**
