### PR TITLE
Add watchOS target in the podspec

### PR DESCRIPTION
**Pull request by igortoliveira**

### CODE REVIEW

**Comment by cocojoe** [comment]
Curious as to why you would need to decode a JWT on the Apple Watch?

**Comment by igortoliveira** [comment]
@cocojoe We use it to verify if the access token is expired. Our watch app depends of the iPhone just for the initial sync, after that, it is autonomous.

**Comment by cocojoe** [comment]
If you can get your PR to pass tests that would be great, thanks.

**Comment by cocojoe** [comment]
Is this still relevant?

**Pull request closed without merging**
